# -*- coding: utf-8 -*-
"""Churn_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUupJgM5eMhpdLy0n6QirNS6qHUZ_YrV

Project Intro
Customer churn is one of the most critical challenges faced by telecom companies, as acquiring new customers is significantly more expensive than retaining existing ones. Even a small increase in churn can lead to substantial revenue loss over time.

This project focuses on performing an end-to-end analysis of customer churn to understand the key factors that influence why customers leave a telecom service provider. Using customer demographic data, account information, service usage details, and payment behavior, the analysis aims to uncover patterns that differentiate churned customers from retained customers.

The goal of this project is not only to identify high-risk customer segments but also to translate analytical findings into practical, business-driven recommendations that can help improve customer retention, enhance service quality, and increase long-term customer loyalty.
"""

import numpy as np;
import pandas as pd;
import seaborn as sns;
from pandas import Series,DataFrame
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Customer Churn.csv");
df.head()

df.info()

df["TotalCharges"].value_counts()

#replace banks with 0 and change the data type
df["TotalCharges"] = df["TotalCharges"].replace(" " , "0")
df["TotalCharges"] = df["TotalCharges"].astype("float")

def convert_values(value):
  if value == 1:
    return "yes"
  else:
    return "no"


df["SeniorCitizen"] =  df["SeniorCitizen"].apply(convert_values)

df.head()

df.describe()

ax = sns.countplot( x = 'Churn' , data = df )
ax.bar_label( ax.containers[0] )
plt.title("count of Customer by Churn")
plt.show()

"""1869 Customers churned out

What type of customers are churning out and what company can do to improve retention rate ?
"""

sns.countplot( x = "gender" , data = df , hue = "Churn"  )
plt.title("churn by Gender")
plt.show()

ax = sns.countplot( x = "SeniorCitizen" , data = df , hue = df["Churn"] )
ax.bar_label(ax.containers[0]  )
plt.title("Count of Customer by Senior citizen")
plt.show()

sns.histplot(  x =  "tenure"   ,  data = df , bins = 72  , hue = "Churn" )
plt.show()

df["Contract"].value_counts()

ax = sns.countplot( x = "Contract"  , data = df  , hue = "Churn" )
ax.bar_label( ax.containers[0] )
plt.title("Count of Customers by Contract")
plt.show()

df.columns

columns = [
    'PhoneService', 'MultipleLines', 'InternetService',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies'
]

plt.figure(figsize=(20, 14))

for i, col in enumerate(columns, 1):
    ax = plt.subplot(3, 3, i)
    sns.countplot(x=col, data=df, hue="Churn", ax=ax)
    ax.set_title(col)
    ax.tick_params(axis='x', rotation=45)

    # Add count labels on bars
    for container in ax.containers:
        ax.bar_label(container, label_type='edge', fontsize=9)

plt.tight_layout()
plt.show()

ax = sns.countplot( x = "PaymentMethod" , data = df , hue = "Churn" )
plt.xticks( rotation = 60 )
ax.bar_label( ax.containers[0] )
ax.bar_label( ax.containers[1] )
plt.show()

"""Final Recommedation
Based on the insights derived from the analysis, the following recommendations can help the company reduce churn and improve overall customer satisfaction:

Improve Early-Stage Customer Engagement
Customers with shorter tenure show significantly higher churn. Introducing structured onboarding programs, proactive follow-ups, and early support within the first few months can help build trust and reduce early exits.

Focus on Senior Citizen Retention
With a high churn rate among senior citizens, the company should offer simplified plans, clearer billing, and priority customer support tailored to this segment.

Encourage Long-Term Contracts
Month-to-month contract customers churn more frequently. Offering discounts, bundled benefits, or loyalty rewards for one-year and two-year contracts can increase commitment and reduce churn.

Bundle Value-Added Services
Customers without online security, backup, device protection, or tech support are more likely to churn. Bundling these services at a discounted rate can increase perceived value and improve retention.

Enhance Fiber Optic Service Experience
Higher churn among fiber optic users suggests possible service quality or support issues. Improving installation quality, network reliability, and proactive technical assistance can help retain these customers.

Promote Automatic Payment Methods
Customers using automatic bank transfers or credit card payments churn less. Encouraging auto-pay through incentives and simplified setup can reduce payment-related churn.
"""
